version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@8.0.0
  aws-ecs: circleci/aws-ecs@2.2.1
  terraform: circleci/terraform@3.0.1

workflows:
  version: 2
  build_and_push_image:
    jobs:
      - aws-ecr/build-and-push-image:
          repo: ${ECR_REPO}
          region: ${AWS_DEFAULT_REGION}
          tag: "${CIRCLE_SHA1}"
          create-repo: true
          dockerfile: Dockerfile
          path: .
      - aws-ecs/deploy-service-update:
          cluster-name: ${CLUSTER_NAME}
          container-image-name-updates: "container=${CONTAINER_NAME},tag=${CIRCLE_SHA1}"
          family: ${CONTAINER_NAME}
          service-name: "${CONTAINER_NAME}-service"
          requires:
            - aws-ecr/build-and-push-image
