version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@8.0.0
  aws-ecs: circleci/aws-ecs@2.2.1
  terraform: circleci/terraform@3.0.1

workflows:
  version: 2
  build_and_push_image:
    jobs:
      - aws-ecr/build-and-push-image:
          repo: sit-sre-digital-ecr
          region: ${AWS_DEFAULT_REGION}
          tag: "${CIRCLE_SHA1}"
          create-repo: true
          dockerfile: Dockerfile
          path: ./emoji-search/
      - aws-ecs/deploy-service-update:
          cluster-name: "sit-sre-digital-ecs"
          container-image-name-updates: "container=sit-sre-digital,tag=${CIRCLE_SHA1}"
          family: "sit-sre-digital"
          service-name: "sit-sre-digital-service"
          requires:
            - aws-ecr/build-and-push-image
